language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install

script: ./vendor/bin/simple-phpunit

matrix:
    include:
        - php: 5.3
          dist: precise
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
    fast_finish: true